# Generated by Django 4.2.5 on 2023-09-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=28)),
                ("description_text", models.CharField(max_length=4000)),
                ("persistence", models.BooleanField(default=False)),
                ("time_end", models.DateField()),
                (
                    "length",
                    models.CharField(
                        choices=[
                            ("day", "Within this Day"),
                            ("week", "Within this Week"),
                            ("month", "Within this Month"),
                            ("year", "Within this Year"),
                        ],
                        default="day",
                        max_length=28,
                    ),
                ),
            ],
        ),
    ]
