# Generated by Django 4.2.5 on 2023-09-08 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_remove_tasks_time_end_tasks_time_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="time_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
